name: Hello CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Say-Hello:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo "Hello CI/CD"
      - run: echo "Author is ${{ github.actor }} on ${{ github.ref }}"
